spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434/
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: llama3.2
          temperature: 0.7
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        #dimensions: 1536
        dimensions: 1024 # ollama llama3.2 default dimensions = 1024
        table-name: hotel_vector
        initialize-schema: true

logging:
  level:
    org:
      springframework:
        ai=DEBUG:
# docker run -it --rm --name postgres2 -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres pgvector/pgvector:pg16