spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
#      base-url: http://192.168.0.2:11434/ # remote
      base-url: http://localhost:11434/ # local
      init:
        pull-model-strategy: when_missing
      chat:
        options:
#          model: llama3.3 # remote
#          model: llama3.2 # local-1
          model: exaone3.5 # local-2
          temperature: 0.3
#      embedding:
#        options:
#          model: mxbai-embed-large # default
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024 # ollama embedding model default - mxbai-embed-large
#        dimensions: 8192 # llama 3.3 # remote
#        dimensions: 3072 # llama3.2
#        dimensions: 1536 # open ai embedding model default - text-embedding-ada-002
        table-name: hotel_vector
        initialize-schema: true
logging:
  level:
    org:
      springframework:
        ai=DEBUG:
# docker run -it --rm --name postgres2 -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres pgvector/pgvector:pg16